### ISSUE TITLE
Heatmap disappears when translate in XY directions

### ISSUE THREAD

**Issue by bartbutenaers** [nswamy14/visual-heatmap#20]
Hi @nswamy14,

When I translate the heatmap (in X/Y directions), the heatmap disappears.  I.e. the whole dive beomes white again.

It looks to me that the values arrive correctly:

![image](https://github.com/nswamy14/visual-heatmap/assets/14224149/925dded2-e02e-4b21-9e66-4b29b460f173)

Do you have any idea what could cause this?

Thanks!
Bart

**Comment by nswamy14** [comment]
Hi @bartbutenaers,

   Is it possible to share an env instance to reproduce the issue? It will help in debugging. Or share the snapshot of values configured for params: - height, width, devicePixel ratio, size, intensity, zoom, angle, opacity, max, min.

Thanks,
Nswamy

**Comment by bartbutenaers** [comment]
Hi @nswamy14,

Did some further debugging myself, and at the end it appeared that the issue was in my own code:
Seems I had forgotten to add a `break` in the "setTranslate" switch-case:

![image](https://github.com/nswamy14/visual-heatmap/assets/14224149/995eeb71-1f8f-46f4-94b6-07064cda4d61)

So immediately afterwards, the heatmap was zoomed (away).
Sorry for the noise!!!

Bart
