### ISSUE TITLE
Adding Typescript support

### ISSUE THREAD

**Issue by Picolas** [nswamy14/visual-heatmap#24]
Hello @nswamy14,

Is there any plan to add Typescript support ?

Thank you,
Nicolas

**Comment by nswamy14** [comment]
Hi @Picolas , 
     Yes, I will be adding TypeScript support in the next upcoming release.
Thanks,
NSwamy

**Comment by nswamy14** [comment]
@Picolas 

New version [v2.1.0](https://www.npmjs.com/package/visual-heatmap) has typescript support. Closing this issue.
