### ISSUE TITLE
Adapt content to canvas width

### ISSUE THREAD

**Issue by diebarral** [nswamy14/visual-heatmap#27]
Hey! 

First of all, thank you for your work on this library, it's been very useful. 

I have one question, cause I'm not sure if it's possible or if there's a workaround for it. The dataset that I'm rendering on the heatmap makes everything look fairly concentrated in the center of the screen, leaving most of the canvas unused, unless I zoom in. 

Is there a way to make the data occupy as much of the canvas width/height as possible, without having to zoom in?

Thanks!

**Comment by nswamy14** [comment]
@diebarral, I hope I've understood your question correctly. You have two options: one is to zoom in, as you have mentioned. The other option is to recalibrate the data coordinates to fit the canvas dimensions (heatmapInstance height/width) and then render the updated data using "renderData" API.

**Comment by diebarral** [comment]
It sounds more like the second option what I want to achieve, so given the width of the canvas and the content, find a "scale" factor to adjust the content to fill as much as possible the size of the rendered canvas? Correct?

**Comment by nswamy14** [comment]
Correct

**Comment by diebarral** [comment]
Alright! Thanks for the quick response!
