### ISSUE TITLE
Does not Work for Some IOS Devices 

### ISSUE THREAD

**Issue by 3TanE** [nswamy14/visual-heatmap#7]
Hi there first of all great library,
but when using it i sadly had issues on ios devies aspecially older ones . Here i encountered the problem that this library uses to many uniforms. The Ipad air 2 only has about 128 to spare. I guessed that your library uses about ~ 230 uniforms. So would there be a way to reduce/cut by half the number of used uniforms without any drawbacks to the performance. 

Greetings Jonathan

**Comment by nswamy14** [comment]
Apologies for the delayed response. I have made updates to the code, reducing the number of uniforms.
